version: '3.9'

services:
    web:
        container_name: web-${APP_ENV}
        build: .
        env_file:
            - .env-${APP_ENV}
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        depends_on:
            - db
        links:
            - db
        ports:
            - ${APP_PORT}:${APP_PORT}
        command: npm run ${APP_ENV}

    db:
        container_name: db-${APP_ENV}
        image: postgres:latest
        restart: unless-stopped
        env_file:
            - .env-${APP_ENV}
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        volumes:
            - dbdata-volume:/data/postgres
        ports:
            - ${DB_PORT}:5432

volumes:
    dbdata-volume: